---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "7b9e595437af1cd3f5d5e374df498c34694d377c"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "iot"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "camel-ose-springboot-xml"
    version: "1.0.0-SNAPSHOT"
    group: "com.demo"
  name: "camel-ose-springboot-xml"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "camel-ose-springboot-xml"
    provider: "fabric8"
    group: "com.demo"
