---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/git-commit: "7b9e595437af1cd3f5d5e374df498c34694d377c"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "iot"
    fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=camel-ose-springboot-xml&var-version=1.0.0-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "camel-ose-springboot-xml"
    version: "1.0.0-SNAPSHOT"
    group: "com.demo"
  name: "camel-ose-springboot-xml"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "camel-ose-springboot-xml"
      provider: "fabric8"
      group: "com.demo"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "7b9e595437af1cd3f5d5e374df498c34694d377c"
        fabric8.io/iconUrl: "img/icons/camel.svg"
        fabric8.io/git-branch: "iot"
        fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=camel-ose-springboot-xml&var-version=1.0.0-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "camel-ose-springboot-xml"
        version: "1.0.0-SNAPSHOT"
        group: "com.demo"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "demo/camel-ose-springboot-xml:snapshot-171015-230458-0693"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 180
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
